#!/bin/bash
#PBS -A abc-123-aa 
#PBS -l walltime=30:00:00
#PBS -l nodes=2:ppn=8
#PBS -q queue
#PBS -r n

# remember to replace abc-123-aa with your sponsor's CCRI id before launching the job

cd $SCRATCH
wget https://dl.dropboxusercontent.com/u/30969719/SRR1777876_accepted_hits_R1.fq.gz
wget https://dl.dropboxusercontent.com/u/30969719/SRR1777876_accepted_hits_R2.fq.gz 
wget https://dl.dropboxusercontent.com/u/30969719/SRR1777877_accepted_hits_R1.fq.gz
wget https://dl.dropboxusercontent.com/u/30969719/SRR1777877_accepted_hits_R2.fq.gz
